[workspace]
members = [
    "crates/p2p-client",
    "crates/signaling-server",
    "crates/signaling-protocol",
]
default-members = [
    "crates/p2p-client",
    "crates/signaling-server",
    "crates/signaling-protocol",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "1.0.2"
license = "MIT"
rust-version = "1.95"
